language: python
python:
  - "3.5"
cache:
  directories:
    - $HOME/.cache/pip
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
env:
  global:
    - TRAVIS=true
    # do not load /etc/boto.cfg with Python 3 incompatible plugin
    # https://github.com/travis-ci/travis-ci/issues/5246#issuecomment-166460882
    - BOTO_CONFIG=/tmp/nowhere
script: python manage.py test
services:
  - mongodb