language: python
python:
  - "3.5"
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
env:
  - TRAVIS=true
  - BOTO_CONFIG=/tmp/nowhere
script: python manage.py test
services:
  - mongodb