language: python
python:
  - "3.5"
cache:
  directories:
    - $HOME/.cache/pip
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
env:
  global:
    - TRAVIS=true
    # do not load /etc/boto.cfg with Python 3 incompatible plugin
    # https://github.com/travis-ci/travis-ci/issues/5246#issuecomment-166460882
    - BOTO_CONFIG=/tmp/nowhere
script: python manage.py test
services:
  - mongodb
  
# Current MongoDB version is 2.4.2 as of 2016-04, see https://github.com/travis-ci/travis-ci/issues/3694
# apt-get starts a MongoDB instance so it's not started using before_script
addons:
  apt:
    sources:
      - mongodb-upstart
      - sourceline: 'deb [arch=amd64] http://repo.mongodb.org/apt/ubuntu precise/mongodb-org/3.4 multiverse'
        key_url: 'https://www.mongodb.org/static/pgp/server-3.4.asc'
    packages:
      - mongodb-org-server
      - mongodb-org-shell
    
before_script:
  - mongod --version
